"""add email and is_subscribed to users

Revision ID: 7fdbd0aea8ea
Revises: af079adc69cc
Create Date: 2026-07-02 19:56:43.926994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fdbd0aea8ea'
down_revision: Union[str, Sequence[str], None] = 'af079adc69cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=100),
                                     nullable=False, server_default='unknown@email.com'))
    op.add_column('users', sa.Column('is_subscribed',
                  sa.Integer(), server_default='0', nullable=False))
    op.alter_column('users', 'name',
                    existing_type=sa.VARCHAR(length=100),
                    type_=sa.String(length=50),
                    existing_nullable=True)
    op.drop_column('users', 'is_premium')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_premium', sa.INTEGER(
    ), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.alter_column('users', 'name',
                    existing_type=sa.String(length=50),
                    type_=sa.VARCHAR(length=100),
                    existing_nullable=True)
    op.drop_column('users', 'is_subscribed')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
