"""add contacts

Revision ID: af079adc69cc
Revises: d9ff7e6833d8
Create Date: 2026-06-29 19:37:43.436973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af079adc69cc'
down_revision: Union[str, Sequence[str], None] = 'd9ff7e6833d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_contacts',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(length=50), nullable=False),
                    sa.Column('phone', sa.String(length=15), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('user_feedback', sa.Column(
        'id', sa.Integer(), autoincrement=True, nullable=False))
    op.alter_column('user_feedback', 'feedback',
                    existing_type=sa.VARCHAR(length=256),
                    type_=sa.String(length=500),
                    existing_nullable=True)
    op.add_column('users', sa.Column('is_premium', sa.Integer(),
                  nullable=False, server_default='0'))
    op.alter_column('users', 'name',
                    existing_type=sa.VARCHAR(length=64),
                    type_=sa.String(length=100),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
                    existing_type=sa.String(length=100),
                    type_=sa.VARCHAR(length=64),
                    existing_nullable=True)
    op.drop_column('users', 'is_premium')
    op.alter_column('user_feedback', 'feedback',
                    existing_type=sa.String(length=500),
                    type_=sa.VARCHAR(length=256),
                    existing_nullable=True)
    op.drop_column('user_feedback', 'id')
    op.drop_table('user_contacts')
    # ### end Alembic commands ###
